### ISSUE TITLE
update to bloc 8 

### ISSUE THREAD

**Issue by thorizer** [sunderee/Flutter-AniList#2]
i like the architecture , it would be great if this project gets updated to bloc 8

**Comment by sunderee** [comment]
Yeah, you're absolutely right. I'll update it as soon as I have 1 hour of spare time... Well, this whole project can get updated in so many ways, not kust

**Comment by sunderee** [comment]
Alright, @thorizer, I got the project updated (one BLoC and one cubit, for educational purposes), and I've managed to do some other minor changes to the UI. Not much, but hey, thanks for pointing it out!
